name: CI - PR Validation Frontend

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
      - develop
      - 'release/**'

jobs:

  trivy:
    uses: YeisonLondo/Skorify_DevOps_Prueba/.github/workflows/sca-generic.yml@main