name: Lint Frontend Correcto

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - develop
      - main
      - 'release/**'

jobs:
  lint-frontend:
    uses: YeisonLondo/Skorify_DevOps_Prueba/.github/workflows/lint-frontend.yml@main
